---
title: "About"
format: html
---

## Work Experience

**Data Services Student Assistant, Development and Alumni Relations**

The University of Texas at Dallas (Richardson, Texas)

**Deputy Manager, Research**

Habib University (Karachi, Pakistan)

Developed the Habib University Research Framework providing multiple research funding opportunities for faculty and students.

Managed execution of externally funded projects at Habib University totaling PKR 17 million.

Organized the Summer Research Program involving 12 faculty members and 30 students with a budget of PKR 5 million.

**Researcher, Youth as Research Program**

UNESCO

Conducted research on the impact of Covid-19 on the learning experience of university students in Pakistan.

Presented findings of the research to the Ministry of Federal Education and Professional Training, Pakistan and UNESCO, Pakistan.

**Assistant Manager, School of Business Studies**

Institute of Business Administration (Karachi, Pakistan)

Managed SBS accreditation process with the School Dean and administrated School's strategic planning project.

Assisted the Dean in developing the Center for Innovation in Learning and Ed-Transformation (CILET).

**Assistant Manager, Institutional Research**

Habib University (Karachi, Pakistan)

Managed the Strategic Planning Project with the Office of President to ensure achievement of annual milestones.

Conducted faculty and course evaluations by designing questionnaires, soliciting feedback from students, and presenting findings to the Dean of Faculty and other relevant stakeholders.
